version: '3'

services:
  db:
    ports:
      - 5432:5432
    image: postgres:10-alpine
    container_name: on-demand-envs-poc-postgres-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
