import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from "axios";

export default function Home(props: any) {
  return (
    <div className={styles.container}>
      <Head>
        <title>On Demand Envs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          On Demand Envs
        </h1>
        <h2>Users</h2>
        { props.users.map((user: any) => (
            <div key={user}>
              <p></p>
              <p>{user.id} - {user.email}</p>
            </div>)
          )
        }
      </main>
    </div>
  )
}

export async function getServerSideProps() {
  const result = await axios.get(`${process.env.BACKEND_URL}`);
  return {
    props: {
      users: result.data
    },
  }
}
